name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/LOGO-MIGIVA.png
    - assets/cancel_red.png
    - assets/left_arrow_green.png
    - assets/left_arrow_yelow.png
    - assets/right_arrow_green.png
    - assets/right_arrow_yelow.png
    - assets/double_arrow_black.png
    - assets/turnstile.png

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf